server:
  port: 4000
m3u8host: 192.168.18.201:4000
path:
  index_file_folder: /index/
  media_file_folders:
    - local_path: /Volumes/user/var/media/
      group_name: t
    - local_path: /Volumse/user/var/media1/
      group_name: k  
m3u8:
  target_duration: 10
log:
  syslog:
    filename: /Volumes/user/var/log/otter_hls_server/system
    pattern: -2006-01-02
    level: debug
