server:
  port: 4000
  domainName: http://127.0.0.1:4000/
media:
  mediaRootPath: /Volumes/user/var/media/
  indexRootPath: /index/
m3u8:
  target_duration: 10
log:
  syslog:
    filename: /Volumes/user/var/log/otter_hls_server/system
    pattern: -2006-01-02